# Generated by Django 5.2.4 on 2025-10-12 10:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='is_urgent',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='location',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='contact_person',
            field=models.CharField(default='Medical Staff', max_length=100),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='contact_phone',
            field=models.CharField(default='0123456789', max_length=15),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital_address',
            field=models.TextField(default='UAP Campus, Kuratoli, Dhaka'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital_name',
            field=models.CharField(default='UAP Medical Center', max_length=255),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='needed_by',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the blood is needed by'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='units_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='urgency',
            field=models.CharField(choices=[('normal', '🟢 Normal'), ('urgent', '🟡 Urgent'), ('emergency', '🔴 Emergency')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Additional information for donors'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', '🟡 Pending'), ('accepted', '✅ Accepted'), ('completed', '🟢 Completed'), ('cancelled', '🔴 Cancelled'), ('expired', '⏰ Expired')], default='pending', max_length=20),
        ),
    ]
