# Generated by Django 5.2.4 on 2025-10-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('blood_request', '🔴 New Blood Request'), ('request_accepted', '📌 Request Accepted'), ('request_completed', '🟢 Request Completed'), ('request_cancelled', '🔴 Request Cancelled'), ('donor_available', '🟢 Donor Available'), ('system', '🔵 System Notification')], max_length=20),
        ),
    ]
